# Generated by Django 5.2.14 on 2026-07-22 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Ssenariys sarlavhasi"
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("KIRUVCHI", "Kiruvchi xat"),
                            ("CHIQUVCHI", "Chiquvchi xat"),
                            ("ICHKI_BUYRUQ", "Ichki buyruq"),
                        ],
                        default="KIRUVCHI",
                        max_length=20,
                        verbose_name="Hujjat turi",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Boshlang'ich (Oson)"),
                            ("MEDIUM", "O'rta daraja"),
                            ("HARD", "Yuqori (Murakkab)"),
                        ],
                        default="EASY",
                        max_length=10,
                        verbose_name="Murakkablik",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        verbose_name="Ssenariy tavsifi va topshiriq sharti"
                    ),
                ),
                (
                    "initial_doc_data",
                    models.JSONField(
                        default=dict,
                        help_text="Hujjatning dastlabki ko'rinishi (raqam, sana, chiquvchi idora, qisqacha mazmun, fayl)",
                    ),
                ),
                (
                    "expected_steps",
                    models.JSONField(
                        default=list,
                        help_text="To'g'ri bajarilishi kerak bo'lgan bosqichlar ketma-ketligi",
                    ),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(default=100, verbose_name="Mukofot XP"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Simulyatsiya ssenariysi",
                "verbose_name_plural": "Simulyatsiya ssenariylari",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SimulationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_step_index",
                    models.IntegerField(default=0, verbose_name="Hozirgi bosqich"),
                ),
                (
                    "performed_actions",
                    models.JSONField(
                        default=list,
                        help_text="Foydalanuvchi tomonidan bajarilgan harakatlar tarixi",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(default=0, verbose_name="To'plangan XP ball"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Bajarildi"),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="simulator.simulationscenario",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulyatsiya sessiyasi",
                "verbose_name_plural": "Simulyatsiya sessiyalari",
                "unique_together": {("user", "scenario")},
            },
        ),
    ]
