# Generated by Django 5.2.14 on 2026-07-24 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulator", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simulationscenario",
            options={
                "ordering": ["id"],
                "verbose_name": "simulation scenario",
                "verbose_name_plural": "simulation scenarios",
            },
        ),
        migrations.AlterModelOptions(
            name="simulationsession",
            options={
                "verbose_name": "simulation session",
                "verbose_name_plural": "simulation sessions",
            },
        ),
        migrations.AlterField(
            model_name="simulationscenario",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="simulationscenario",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="simulationscenario",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("EASY", "Beginner (Easy)"),
                    ("MEDIUM", "Intermediate"),
                    ("HARD", "Advanced (Complex)"),
                ],
                default="EASY",
                max_length=10,
                verbose_name="difficulty",
            ),
        ),
        migrations.AlterField(
            model_name="simulationscenario",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("KIRUVCHI", "Incoming mail"),
                    ("CHIQUVCHI", "Outgoing mail"),
                    ("ICHKI_BUYRUQ", "Internal order"),
                ],
                default="KIRUVCHI",
                max_length=20,
                verbose_name="document type",
            ),
        ),
        migrations.AlterField(
            model_name="simulationscenario",
            name="expected_steps",
            field=models.JSONField(
                default=list,
                help_text="Sequence of steps that must be completed correctly",
            ),
        ),
        migrations.AlterField(
            model_name="simulationscenario",
            name="initial_doc_data",
            field=models.JSONField(
                default=dict,
                help_text="Initial layout of the document (number, date, outgoing organization, summary, file)",
            ),
        ),
        migrations.AlterField(
            model_name="simulationscenario",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AlterField(
            model_name="simulationscenario",
            name="title",
            field=models.CharField(max_length=255, verbose_name="scenario title"),
        ),
        migrations.AlterField(
            model_name="simulationscenario",
            name="xp_reward",
            field=models.PositiveIntegerField(default=100, verbose_name="XP reward"),
        ),
        migrations.AlterField(
            model_name="simulationsession",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="completed at"
            ),
        ),
        migrations.AlterField(
            model_name="simulationsession",
            name="current_step_index",
            field=models.IntegerField(default=0, verbose_name="current step"),
        ),
        migrations.AlterField(
            model_name="simulationsession",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="is completed"),
        ),
        migrations.AlterField(
            model_name="simulationsession",
            name="performed_actions",
            field=models.JSONField(
                default=list, help_text="History of actions performed by the user"
            ),
        ),
        migrations.AlterField(
            model_name="simulationsession",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="simulator.simulationscenario",
                verbose_name="scenario",
            ),
        ),
        migrations.AlterField(
            model_name="simulationsession",
            name="score",
            field=models.IntegerField(default=0, verbose_name="XP score"),
        ),
        migrations.AlterField(
            model_name="simulationsession",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="started at"),
        ),
        migrations.AlterField(
            model_name="simulationsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simulation_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.CreateModel(
            name="IncomingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(max_length=50, verbose_name="document number"),
                ),
                ("doc_date", models.DateField(verbose_name="document date")),
                (
                    "sender",
                    models.CharField(
                        max_length=255, verbose_name="sender organization"
                    ),
                ),
                ("subject", models.TextField(verbose_name="subject/content summary")),
                (
                    "doc_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="document name"
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="reference type"
                    ),
                ),
                (
                    "executor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="executor"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "incoming_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="incoming number"
                    ),
                ),
                (
                    "outgoing_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="outgoing number"
                    ),
                ),
                (
                    "incoming_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="incoming date"
                    ),
                ),
                (
                    "outgoing_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="outgoing date"
                    ),
                ),
                (
                    "execution_instruction",
                    models.TextField(blank=True, verbose_name="execution instruction"),
                ),
                (
                    "state_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("geographic", "Qo'riqchi o'qurganlar"),
                            ("state", "O'qarlabiga"),
                        ],
                        max_length=50,
                        verbose_name="state type",
                    ),
                ),
                (
                    "action_field",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="action field"
                    ),
                ),
                (
                    "external_corp",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="external corporation"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="incoming_documents/%Y/%m/",
                        verbose_name="PDF file",
                    ),
                ),
                (
                    "is_registered",
                    models.BooleanField(default=False, verbose_name="is registered"),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="registered at"
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="signed at"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="received at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registered by",
                    ),
                ),
            ],
            options={
                "verbose_name": "incoming document",
                "verbose_name_plural": "incoming documents",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["doc_number"], name="simulator_i_doc_num_be7d37_idx"
                    ),
                    models.Index(
                        fields=["doc_date"], name="simulator_i_doc_dat_817e38_idx"
                    ),
                    models.Index(
                        fields=["is_registered"], name="simulator_i_is_regi_e0cf97_idx"
                    ),
                ],
            },
        ),
    ]
