# Generated by Django 5.0.6 on 2026-07-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="max_attempts",
            field=models.PositiveIntegerField(
                blank=True,
                default=6,
                help_text="Maksimal urinishlar soni. Bo'sh yoki 0 bo'lsa - cheksiz.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="max_attempts",
            field=models.PositiveIntegerField(
                blank=True,
                default=6,
                help_text="Maksimal urinishlar soni. Bo'sh yoki 0 bo'lsa - cheksiz.",
                null=True,
            ),
        ),
    ]
