# Generated by Django 5.2.14 on 2026-07-22 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0003_quizattempt_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizattempt",
            name="duration",
        ),
    ]
